# Generated by Django 2.2.16 on 2022-07-27 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220727_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Код для получения/обновления токена'),
        ),
    ]
