# Generated by Django 2.2.16 on 2022-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Films', 'Фильмы'), ('Books', 'Книги'), ('Music', 'Музыка')], max_length=16)),
            ],
        ),
    ]
