# Generated by Django 2.2.16 on 2022-07-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220727_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='description',
        ),
    ]
