# Generated by Django 2.2.16 on 2022-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220729_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(),
        ),
    ]
